import { defineComponent, h, type Component, type CSSProperties } from 'vue'
import {
  AtSign, Box, PanelLeft, Sparkles, SquareCheck, Star, Sun,
  Activity,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  BadgeCheck,
  Bell,
  Bold,
  BookOpen,
  Bookmark,
  BookmarkPlus,
  Brain,
  Bug,
  Building2,
  Cable,
  CalendarDays,
  Cast,
  ChartColumn,
  ChartLine,
  ChartScatter,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  CircleAlert,
  CircleArrowRight,
  CircleCheck,
  CircleChevronRight,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CircleStop,
  CircleUserRound,
  CircleX,
  ClipboardPaste,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Copy,
  CornerDownLeft,
  Database,
  DatabaseSearch,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FilePlus,
  Presentation,
  FileQuestionMark,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Fish,
  FlipHorizontal,
  Focus,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  GitFork,
  Globe,
  Highlighter,
  History,
  House,
  Image,
  ImageOff,
  Import,
  Info,
  Italic,
  KeyRound,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Maximize,
  MessageCircle,
  MessageCirclePlus,
  MessageCircleQuestionMark,
  Minimize,
  Minus,
  MousePointer2,
  Move,
  Network,
  NotebookPen,
  PackagePlus,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Power,
  Puzzle,
  QrCode,
  Quote,
  RectangleHorizontal,
  RefreshCw,
  RotateCw,
  Rss,
  Save,
  Search,
  Send,
  SeparatorHorizontal,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  Sigma,
  SkipBack,
  SkipForward,
  Square,
  SquareMinus,
  SquarePlus,
  Strikethrough,
  Table,
  Tag,
  Tags,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  UserPlus,
  UserRoundX,
  Users,
  Video,
  Workflow,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from '@lucide/vue'

/** Offline Lucide names shared by application icons and TDesign defaults. */
export const iconComponents: Readonly<Record<string, Component>> = {
  'at': AtSign,
  'box': Box,
  'panel-left': PanelLeft,
  'sparkles': Sparkles,
  'sun': Sun,
  'activity': Activity,
  'add': Plus,
  'add-rectangle': SquarePlus,
  'ai-search': Brain,
  'api': Cable,
  'app': LayoutGrid,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-circle': CircleArrowRight,
  'arrow-triangle-down-filled': ChevronDown,
  'arrow-triangle-up-filled': ChevronUp,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'attach': Paperclip,
  'audio': AudioLines,
  'automation': Workflow,
  'backtop': ChevronsUp,
  'book': BookOpen,
  'bookmark': Bookmark,
  'bookmark-add': BookmarkPlus,
  'bridge': Cable,
  'browse': Eye,
  'browse-off': EyeOff,
  'bug': Bug,
  'building': Building2,
  'bulletpoint': List,
  'button': RectangleHorizontal,
  'calendar': CalendarDays,
  'caret-right-small': ChevronRight,
  'cast': Cast,
  'catalog': List,
  'chart-bar': ChartColumn,
  'chart-bubble': ChartScatter,
  'chart-line': ChartLine,
  'chat': MessageCircle,
  'chat-add': MessageCirclePlus,
  'chat-bubble': MessageCircle,
  'chat-bubble-help': MessageCircleQuestionMark,
  'chat-bubble-history': History,
  'chat-message': MessageCircle,
  'check': Check,
  'check-circle': CircleCheck,
  'check-circle-filled': CircleCheck,
  'check-rectangle': SquareCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-left-double': ChevronsLeft,
  'chevron-right': ChevronRight,
  'chevron-right-circle': CircleChevronRight,
  'chevron-right-double': ChevronsRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'clear': Eraser,
  'close': X,
  'close-circle': CircleX,
  'close-circle-filled': CircleX,
  'cloud': Cloud,
  'cloud-download': CloudDownload,
  'cloud-upload': CloudUpload,
  'code': Code,
  'component-divider-horizontal': SeparatorHorizontal,
  'control-platform': Workflow,
  'copy': Copy,
  'cursor': MousePointer2,
  'data': Database,
  'data-base': Database,
  'data-search': DatabaseSearch,
  'delete': Trash2,
  'discount': Tags,
  'download': Download,
  'draft': NotebookPen,
  'edit': Pencil,
  'edit-1': Pencil,
  'ellipsis': Ellipsis,
  'enter': CornerDownLeft,
  'error': TriangleAlert,
  'error-circle': CircleAlert,
  'error-circle-filled': CircleAlert,
  'export': Download,
  'extension': Puzzle,
  'file': File,
  'file-add': FilePlus,
  'file-code': FileCode,
  'file-copy': Copy,
  'file-excel': FileSpreadsheet,
  'file-icon': File,
  'file-paste': ClipboardPaste,
  'file-pdf': FileText,
  'file-powerpoint': Presentation,
  'file-search': FileSearch,
  'file-unknown': FileQuestionMark,
  'file-view': FileSearch,
  'file-word': FileText,
  'filter': ListFilter,
  'filter-sort': ListFilter,
  'fish': Fish,
  'focus': Focus,
  'folder': Folder,
  'folder-add': FolderPlus,
  'folder-open': FolderOpen,
  'form': ListChecks,
  'fullscreen': Maximize,
  'fullscreen-exit': Minimize,
  'git-branch': GitBranch,
  'global': Globe,
  'help': CircleHelp,
  'help-circle': CircleHelp,
  'help-circle-filled': CircleHelp,
  'highlight': Highlighter,
  'history': History,
  'home': House,
  'https': Lock,
  'icon': CircleHelp,
  'image': Image,
  'image-error': ImageOff,
  'import': Import,
  'info-circle': Info,
  'info-circle-filled': Info,
  'install': PackagePlus,
  'integration': Cable,
  'internet': Globe,
  'jump': ArrowUpRight,
  'key': KeyRound,
  'layers': Layers,
  'lightbulb': Lightbulb,
  'link': Link,
  'list-numbered': ListOrdered,
  'load': LoaderCircle,
  'loading': LoaderCircle,
  'lock-on': Lock,
  'login': LogIn,
  'logo-github': GitFork,
  'logout': LogOut,
  'mail': Mail,
  'member': Users,
  'menu': List,
  'mermaid': Network,
  'minus-circle': CircleMinus,
  'minus-circle-filled': CircleMinus,
  'minus-rectangle': SquareMinus,
  'mirror': FlipHorizontal,
  'more': Ellipsis,
  'move': Move,
  'next': ArrowRight,
  'notification': Bell,
  'page-first': SkipBack,
  'page-last': SkipForward,
  'pause-circle': CirclePause,
  'pending': LoaderCircle,
  'pin': Pin,
  'pin-filled': Pin,
  'placeholder': RectangleHorizontal,
  'play-circle': CirclePlay,
  'play-circle-filled': CirclePlay,
  'play-circle-stroke': CirclePlay,
  'poweroff': Power,
  'qrcode': QrCode,
  'queue': List,
  'quote': Quote,
  'refresh': RefreshCw,
  'relation': Link,
  'relativity': Link,
  'remove': Minus,
  'rename': Pencil,
  'rollback': Undo2,
  'root-list': List,
  'rotate': RotateCw,
  'rotation': RotateCw,
  'round': Circle,
  'rss': Rss,
  'save': Save,
  'scan': Focus,
  'search': Search,
  'secured': ShieldCheck,
  'send': Send,
  'server': Server,
  'service': Workflow,
  'setting': Settings,
  'share': Share2,
  'shortcut': ExternalLink,
  'sound': AudioLines,
  'space': LayoutGrid,
  'star': Star,
  'star-filled': Star,
  'stop': Square,
  'stop-circle': CircleStop,
  'subtitle': FileText,
  'sum': Sigma,
  'summary': BookOpen,
  'swap': ArrowLeftRight,
  'system-code': Code,
  'system-sum': LayoutGrid,
  'tab': RectangleHorizontal,
  'table': Table,
  'tag': Tag,
  'task': ListChecks,
  'template': LayoutTemplate,
  'terminal': Terminal,
  'text': FileText,
  'textformat-bold': Bold,
  'textformat-italic': Italic,
  'textformat-strikethrough': Strikethrough,
  'time': Clock,
  'time-filled': Clock,
  'tools': Wrench,
  'transform': ArrowLeftRight,
  'tree-list': List,
  'upload': Upload,
  'user': User,
  'user-add': UserPlus,
  'user-avatar': CircleUserRound,
  'user-circle': CircleUserRound,
  'user-clear': UserRoundX,
  'user-safety': ShieldCheck,
  'user-vip-filled': BadgeCheck,
  'usergroup': Users,
  'usergroup-add': UserPlus,
  'verify': Check,
  'vertical': EllipsisVertical,
  'video': Video,
  'view-list': List,
  'view-module': LayoutGrid,
  'web': Globe,
  'widget': LayoutGrid,
  'work': Building2,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}

const warned = new Set<string>()
export function resolveLucideIcon(name: string): Component {
  const component = Object.hasOwn(iconComponents, name) ? iconComponents[name] : undefined
  if (component) return component
  if (!warned.has(name)) {
    warned.add(name)
    console.warn(`[icons] Unknown icon "${name}"; rendering Lucide CircleHelp.`)
  }
  return CircleHelp
}

const iconProps = {
  name: { type: String, default: '' },
  size: { type: [String, Number], default: '1em' },
  strokeWidth: { type: [String, Number], default: 1.75 },
  rotate: { type: [String, Number], default: 0 },
  spin: Boolean,
}

function iconComponent(fixedName?: string) {
  return defineComponent({
    name: fixedName ? `LucideCompat-${fixedName}` : 'TIcon',
    inheritAttrs: false,
    props: iconProps,
    setup(props, { attrs }) {
      return () => {
        const name = fixedName ?? props.name
        const component = resolveLucideIcon(name)
        const rotate = Number(props.rotate)
        return h(component, {
          ...attrs,
          size: props.size,
          strokeWidth: props.strokeWidth,
          class: ['t-icon', `t-icon-${name}`, { 'app-icon-spin': props.spin || name === 'loading' }, attrs.class],
          style: [Number.isFinite(rotate) && rotate ? { transform: `rotate(${rotate}deg)` } : {}, attrs.style] as CSSProperties[],
          'data-icon-library': 'lucide',
          'data-icon-name': name,
          'data-icon-fallback': Object.hasOwn(iconComponents, name) ? undefined : 'true',
          'aria-hidden': attrs['aria-hidden'] ?? (attrs['aria-label'] || attrs['aria-labelledby'] || attrs.role ? undefined : true),
        })
      }
    },
  })
}

export const Icon = iconComponent()
export const IconFont = Icon
export type GlobalIconConfig = Partial<Record<string, Component>>
export const AddIcon = iconComponent('add')
export const AddRectangleIcon = iconComponent('add-rectangle')
export const ArrowTriangleDownFilledIcon = iconComponent('arrow-triangle-down-filled')
export const ArrowTriangleUpFilledIcon = iconComponent('arrow-triangle-up-filled')
export const BacktopIcon = iconComponent('backtop')
export const BrowseIcon = iconComponent('browse')
export const BrowseOffIcon = iconComponent('browse-off')
export const CalendarIcon = iconComponent('calendar')
export const CaretRightSmallIcon = iconComponent('caret-right-small')
export const CheckCircleFilledIcon = iconComponent('check-circle-filled')
export const CheckIcon = iconComponent('check')
export const ChevronDownIcon = iconComponent('chevron-down')
export const ChevronLeftDoubleIcon = iconComponent('chevron-left-double')
export const ChevronLeftIcon = iconComponent('chevron-left')
export const ChevronRightCircleIcon = iconComponent('chevron-right-circle')
export const ChevronRightDoubleIcon = iconComponent('chevron-right-double')
export const ChevronRightIcon = iconComponent('chevron-right')
export const ChevronUpIcon = iconComponent('chevron-up')
export const CloseCircleFilledIcon = iconComponent('close-circle-filled')
export const CloseIcon = iconComponent('close')
export const CopyIcon = iconComponent('copy')
export const DeleteIcon = iconComponent('delete')
export const DownloadIcon = iconComponent('download')
export const Edit1Icon = iconComponent('edit-1')
export const EllipsisIcon = iconComponent('ellipsis')
export const ErrorCircleFilledIcon = iconComponent('error-circle-filled')
export const ErrorCircleIcon = iconComponent('error-circle')
export const ErrorIcon = iconComponent('error')
export const FileCopyIcon = iconComponent('file-copy')
export const FileExcelIcon = iconComponent('file-excel')
export const FileIcon = iconComponent('file')
export const FilePdfIcon = iconComponent('file-pdf')
export const FilePowerpointIcon = iconComponent('file-powerpoint')
export const FileWordIcon = iconComponent('file-word')
export const FilterIcon = iconComponent('filter')
export const FolderIcon = iconComponent('folder')
export const HelpCircleFilledIcon = iconComponent('help-circle-filled')
export const ImageErrorIcon = iconComponent('image-error')
export const ImageIcon = iconComponent('image')
export const InfoCircleFilledIcon = iconComponent('info-circle-filled')
export const MinusRectangleIcon = iconComponent('minus-rectangle')
export const MirrorIcon = iconComponent('mirror')
export const PageFirstIcon = iconComponent('page-first')
export const PageLastIcon = iconComponent('page-last')
export const PlayCircleIcon = iconComponent('play-circle')
export const RefreshIcon = iconComponent('refresh')
export const RemoveIcon = iconComponent('remove')
export const RotationIcon = iconComponent('rotation')
export const RoundIcon = iconComponent('round')
export const SearchIcon = iconComponent('search')
export const SettingIcon = iconComponent('setting')
export const StarFilledIcon = iconComponent('star-filled')
export const TimeFilledIcon = iconComponent('time-filled')
export const TimeIcon = iconComponent('time')
export const UploadIcon = iconComponent('upload')
export const VideoIcon = iconComponent('video')
export const ZoomInIcon = iconComponent('zoom-in')
export const ZoomOutIcon = iconComponent('zoom-out')
